"""Version contracts for the trusted unified router."""

UNIFIED_ROUTER_SCHEMA_VERSION = 1
ROUTE_RECEIPT_SCHEMA_VERSION = 1
TOOL_REGISTRY_SCHEMA_VERSION = 1
CONTROLLED_ROUTER_LANGUAGE_VERSION = 1
ROUTER_STORE_SCHEMA_VERSION = 1
