"""Version contracts for the trusted unified router."""

UNIFIED_ROUTER_SCHEMA_VERSION = 2
ROUTE_RECEIPT_SCHEMA_VERSION = 2
ROUTER_STORE_SCHEMA_VERSION = 2
TOOL_REGISTRY_SCHEMA_VERSION = 2
TOOL_CALL_SCHEMA_VERSION = 2
UNIFIED_RESPONSE_SCHEMA_VERSION = 2
TOOL_IMPLEMENTATION_POLICY_VERSION = "2.0"
ROUTE_POLICY_VERSION = "2.0"
EQUIVALENCE_POLICY_VERSION = "stage2-final-state-v3"
CONTROLLED_ROUTER_LANGUAGE_VERSION = 1
