"""Versioned contracts for the trusted factual-memory package."""

FACT_MEMORY_SCHEMA_VERSION = 1
FACT_MEMORY_MIGRATION_VERSION = 1
FACT_MEMORY_APPLICATION_ID = 0x41494246  # AIBF
FACT_APPROVAL_POLICY_VERSION = "1.0"
FACT_RENDERING_VERSION = "1.0"
DEFAULT_BUSY_TIMEOUT_MS = 5_000
MAX_SOURCE_BYTES = 16 * 1024 * 1024
