"""Versioned contracts for the M-28 chemistry domain."""

CHEMISTRY_DOMAIN_VERSION = "1.0.0"
CHEMISTRY_DOMAIN_SCHEMA_VERSION = 1
CHEMISTRY_SOURCE_POLICY_VERSION = "1.0"
CHEMISTRY_FORMULA_GRAMMAR_VERSION = "1.0"
CHEMISTRY_CALCULATION_POLICY_VERSION = "1.0"
CHEMISTRY_RENDERING_VERSION = "1.0"
CHEMISTRY_ATOMIC_WEIGHT_POLICY = "CONVENTIONAL_CLASSROOM_VALUE_FROM_CIAAW_ABRIDGED_2024"
