"""Generic educational-domain provider boundary."""

from __future__ import annotations

from typing import Protocol


class EducationalDomainProvider(Protocol):
    def domain_runtime(self): ...
    def strict_answer_parser(self, raw, answer_type): ...
    def fact_resolver(self, knowledge_id: str): ...
    def catalog_provider(self): ...
    def graph_compiler_provider(self): ...
    def explanation_provider(self): ...
    def currentness_verifier(self): ...
    def controlled_language_provider(self): ...
    def public_domain_metadata(self): ...
    def present(self, family_id=None, *, seed=0, language="en"): ...
    def grade(self, exercise_id: str, raw_answer): ...
    def hint(self, exercise_id: str): ...
    def explain(self, exercise_id: str): ...
    def replay(self, exercise_id: str): ...
    def progress(self): ...
    def converse(self, text: str, *, exercise_id: str | None = None): ...
