"""Conversational trust-boundary versions."""

CONVERSATIONAL_TUTOR_VERSION = "1.0.0"
CONVERSATIONAL_SCHEMA_VERSION = 1
CONVERSATION_STORE_SCHEMA_VERSION = 1
PENDING_ACTION_SCHEMA_VERSION = 1
CONTROLLED_INTENT_VERSION = "1.0"
