"""Explicit verification/acquisition statuses."""

from __future__ import annotations

from enum import StrEnum


class VerificationStatus(StrEnum):
    FORMALLY_VERIFIED = "FORMALLY_VERIFIED"
    PROPERTY_VERIFIED = "PROPERTY_VERIFIED"
    IDENTIFIED_IN_HYPOTHESIS_SPACE = "IDENTIFIED_IN_HYPOTHESIS_SPACE"
    CONSISTENT_WITH_DEMONSTRATIONS = "CONSISTENT_WITH_DEMONSTRATIONS"
    PROVISIONAL = "PROVISIONAL"
    AMBIGUOUS = "AMBIGUOUS"
    REJECTED = "REJECTED"
    UNSUPPORTED = "UNSUPPORTED"
    SEARCH_BUDGET_EXHAUSTED = "SEARCH_BUDGET_EXHAUSTED"
