UNIVERSAL_KNOWLEDGE_IR_VERSION = "1.0.0"
UNIVERSAL_KNOWLEDGE_IR_SCHEMA_VERSION = 1
DOMAIN_PACK_SCHEMA_VERSION = 1
CAPABILITY_REGISTRY_SCHEMA_VERSION = 1
DOMAIN_REGISTRY_SCHEMA_VERSION = 1
CONCEPT_GRAPH_SCHEMA_VERSION = 1
PACK_APPROVAL_SCHEMA_VERSION = 1
CAPABILITY_RESOLUTION_SCHEMA_VERSION = 1
