"""Frozen Stage-1 production contract versions."""

STAGE1_VERSION = "1.0.1"
CONTROLLED_LANGUAGE_VERSION = "1"
SPECIFICATION_SCHEMA_VERSION = 1
RULE_MEMORY_SCHEMA_VERSION = 1
WORKFLOW_ARTIFACT_SCHEMA_VERSION = 1
EXECUTION_LIMITS_VERSION = "1"
